variables:
  APP_NAME: sdal-landing
  APP_PORT: 80
  DEPLOY_PUBLIC_PORT: 8010
  DEPLOY_NETWORK_NAME: proxy
  DOCKER_IMAGE_NAME: $DOCKER_ORGANIZATION/$APP_NAME
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: clone

stages:
  - publish
  - deploy

publish:
  stage: publish
  image: docker
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
  after_script:
    - docker login --username=$DOCKER_USER --password=$DOCKER_TOKEN
    - docker push $DOCKER_IMAGE_NAME

# DEPLOY

deploy:
  stage: deploy
  image: ictu/sshpass
  needs:
    - publish
  before_script:
    - alias ssh-pass-server='sshpass -p "$SDAL_DEFAULT_PASSWORD" ssh -oStrictHostKeyChecking=no $SDAL_DEFAULT_USERNAME@$SDAL_DEFAULT_IP'
  script:
    - ssh-pass-server docker pull $DOCKER_IMAGE_NAME
    - ssh-pass-server docker rm -f $APP_NAME || true
    - ssh-pass-server docker run -d -p $DEPLOY_PUBLIC_PORT:$APP_PORT --network=$DEPLOY_NETWORK_NAME --name $APP_NAME $DOCKER_IMAGE_NAME
